class Main {
	static void run(){
	
		x= 2;
		d1=3.1415926;
		d2=1e3;
		s="stringurustringurustringurustringurustringurustringurustringurustringurustringurustringurustringurustringurustringurustringurustringurustringurustringurustringurustringurustringurustringurustringurustringurustringurustringurustringurustringurustringurustringurustringurustringurustringurustringurustringurustringurustringurustringurustringurustringurustringurustringurustringurustringurustringurustringurustringurustringurustringurustringuru";
	
	}
}